### ISSUE TITLE
Thumbnails Can Overflow

### ISSUE THREAD

**Issue by ElectronEsq** [OdyseeTeam/odysee-frontend#274]
## Problem:
Custom thumbnails can overflow.

## Solution:
Giving the element the CSS style of `overflow:hidden;` should fix the issue.

## Screenshots:

The issue:

![image](https://user-images.githubusercontent.com/29914179/141287837-1ef2da54-9c3d-4835-a880-f9fc03d30056.png)

The fix:

![image](https://user-images.githubusercontent.com/29914179/141288021-5aaa8920-ad05-4b62-9502-56b86aa5ccab.png)

**Comment by tzarebczan** [comment]
Thanks for the report @ElectronEsq ! Wanna take a shot at a PR?

**Comment by ElectronEsq** [comment]
> Thanks for the report @ElectronEsq ! Wanna take a shot at a PR?

Yeah sure. I've not got the dev environment for it set up, but it's a super simple one that can be adequately tested in dev tools.
I'll locate that `class` now and and append it.

**Comment by ElectronEsq** [comment]
> Thanks for the report @ElectronEsq ! Wanna take a shot at a PR?

After further investigation, it looks like there's an error with the .CSS on line [133](https://github.com/lbryio/lbry-desktop/blob/bba0630890d95bd622cb9510425abc2c45a7aeac/ui/scss/component/_notification.scss#L133).

Because it might be that creating this issue; rather than adding to the code with `overflow:hidden;`, it might be better to test with the below fix first.

## Error on line 2.
```css
  @media (min-width: $breakpoint-small) {
    height: thumbnailWidth; /*Invalid SCSS*/
    width: calc(#{$thumbnailWidth} * 16 / 9);
    max-width: calc(#{$thumbnailWidth} * 16 / 9);
    margin-left: var(--spacing-m);
    margin-top: 0;
    min-width: 0;
  }
}
```
## Fix on line 2.
It should be something like this, which uses a var `height: var(--thumbnailWidth);`.
```css
  @media (min-width: $breakpoint-small) {
    height: var(--thumbnailWidth); /*Valid SCSS*/
    width: calc(#{$thumbnailWidth} * 16 / 9);
    max-width: calc(#{$thumbnailWidth} * 16 / 9);
    margin-left: var(--spacing-m);
    margin-top: 0;
    min-width: 0;
  }
}
```
However, it might be that it's meant to use a `calc` function, rather than a `var`.

The error/overflowing thumb, isn't there anymore to test it with. I'd have to set up the dev environment, then artificially recreate the error.

I might be able to do that after the weekend if no one else can do this quicker.
