### ISSUE TITLE
Comments section too wide on wide monitors for posts

### ISSUE THREAD

**Issue by QuirkyRobots** [OdyseeTeam/odysee-frontend#870]
The comments section is wider than the post section, on wide monitors, as seen [here](https://odysee.com/@Alojz:f/claim-timelocked-lbc:2).
This is especially obvious on ultra widescreen monitors.

The posts are set to `width: 52rem;` for monitors wider than 1600px. But the comments are not.
```css
@media (min-width: 1600px) {
    .post {
        width: 52rem; 
    }
}
```
A potential fix could be this.
```css
@media (min-width: 1600px) {
    .file-page__post-comments .card__first-pane {
        width: 52rem; 
        margin: 0 auto;
     }
}     
```

Current issue:

![image](https://user-images.githubusercontent.com/29914179/154003123-8d666752-1c25-4020-aaca-440c2c1c7e93.png)

How it looks with the above CSS fix:

![image](https://user-images.githubusercontent.com/29914179/154005749-6fdbbe41-ce97-4b66-9307-8f50ab81e71f.png)

A fixed version can be previewed on the [Nomics, Odysee custom theme.](https://userstyles.org/styles/221708/odysee-user-feedback-theme) However, this uses a different method.

![image](https://user-images.githubusercontent.com/29914179/154013159-49101253-ed19-45bc-8930-d5714e76b917.png)
